name: CI
on:
  pull_request:
  push:
jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4.3.0
      - run: npm ci
      - run: npm run build
      - run: npm run lint:ci

  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4.3.0
      - run: npm ci
      - run: cp .env.testing .env
      - run: docker compose -f docker-compose.yml --env-file .env.testing up -d
      - run: npm run build
      - run: npm run start &
      - run: npm run prepare-test
      - run: npm run test


